name: 'Stage Verifier'
on:
  pull-request:
  push:
    branches:
      - main

jobs:
  check_deploy_test_verify:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Logsight Setup
        uses: aiops/logsight-setup-action@main
        id: setup
        with:
          username: ${{ secrets.LOGSIGHT_USERNAME }}
          password: ${{ secrets.LOGSIGHT_PASSWORD }}
          application_name: ${{ github.ref }}
          fluentbit_filelocation: /host$GITHUB_WORKSPACE/*.log
          fluentbit_message: 'log'

      - name: Set up Python 3.9.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.6

      - name: Run Hello Logsight
        run: python hello_logsight.py

      - name: Verify Logs
        uses: aiops/logsight-verification-action@main
        id: verify-logs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ secrets.LOGSIGHT_USERNAME }}
          password: ${{ secrets.LOGSIGHT_PASSWORD }}
          application_id: ${{ steps.setup.outputs.application_id }}
          baseline_tag: ${{ github.event.before }}
          candidate_tag: ${{ github.sha }}
          risk_threshold: 10