name: 'Stage Verifier (Pull)'
on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]

jobs:
  deployment_risk:
    runs-on: ubuntu-latest
    steps:

      - name: Logsight Setup
        uses: aiops/logsight-setup-action@v1.0.0
        id: setup
        with:
          username: ${{ secrets.LOGSIGHT_USERNAME }}
          password: ${{ secrets.LOGSIGHT_PASSWORD }}
          application_name: ${{ github.repository }}
          fluentbit_filelocation: /host$GITHUB_WORKSPACE/*.log
          fluentbit_message: 'log'
          tag: ${{ github.event.pull_request.head.sha }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"

      - name: Run Hello Logsight
        run: python hello_logsight.py

      - name: Debug
        run: |
          ls
          pwd

      - uses: actions/checkout@v2
      - name: Verify Logs
        uses: aiops/logsight-verification-action@v1.0.0
        id: verify-logs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ secrets.LOGSIGHT_USERNAME }}
          password: ${{ secrets.LOGSIGHT_PASSWORD }}
          application_id: ${{ steps.setup.outputs.application_id }}
          baseline_tag: ${{ github.event.pull_request.base.sha }}
          candidate_tag: ${{ github.event.pull_request.head.sha }}
          risk_threshold: 10