name: 'Stage Verifier (Push) demo'
on:
  push:
    branches:
      - '*'

jobs:
  deployment_risk:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Logsight Setup
        uses: aiops/logsight-setup-action@v1.1.0
        id: setup
        with:
          username: ${{ secrets.LOGSIGHT_USERNAME }}
          password: ${{ secrets.LOGSIGHT_PASSWORD }}
          application_name: ${{ github.repository }}
          fluentbit_filelocation: /host$GITHUB_WORKSPACE/*.log
          fluentbit_message: 'log'
          tag: ${{ github.sha }}

      - name: Run Hello Logsight
        run: python hello_logsight.py

      - name: Verify Logs
        uses: aiops/logsight-verification-action@v1.1.0
        id: verify-logs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ secrets.LOGSIGHT_USERNAME }}
          password: ${{ secrets.LOGSIGHT_PASSWORD }}
          application_name: ${{ steps.setup.outputs.application_name }}
          baseline_tag: ${{ github.event.before }}
          candidate_tag: ${{ github.sha }}
          risk_threshold: 10